<img src="./figures/NumPy_logo.svg" alt="Indentation" width="30%" height="30%">


# Utilisation de la librairie Numpy  (Numerical Python)


- Bibliothèque importante en Python en calcul scientifique, cette librairie est appelée dans beaucoup d'autres librairies

- Intègre une nouvelle structure de données: les ndarray (N-dimensional array). Ce sont des vecteurs (tableaux à 1 dimension), tableaux à plusieurs dimensions

- Intègre un ensemble de fonctions développées en C. Calcul performant sur les calculs 

- Utilisé dans tous les projets de calculs numériques 

- Les ndarray se manipulent comme les listes et les tubles MAIS ne peut contenir qu'un seul type de données.



Nous allons voir comment initialiser des tableaux Numpy de plusieurs façons, accéder aux valeurs dans les tableaux, effectuer des opérations mathématiques et matricielles, et utiliser des tableaux aussi bien pour le masquage que pour les comparaisons. 
 

## 1- Création d'un tableau Numpy ou ndarray
 
Tout d’abord, vous devez importer Numpy avec le code suivant:

In [1]:
# On va importer la librairie Numpy et créer un alias. 
# Les alias permettent d'alléger l'écriture des codes. 
import numpy as np

Contrairement à une liste, vous ne pouvez pas créer de tableaux Numpy vides. Vous trouverez ci-dessous plusieurs façons d’initialiser un tableau Numpy en fonction de vos besoins:

- Utilisation de la fonction <b>array()</b> pour créer un tableau Numpy:

In [2]:
tableau1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
tableau1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

Création d'un tableau bi-dimensionnel avec des lignes et des colonnes; on crée une liste de liste. Chaque liste est une ligne du tableau.

In [3]:
# Exemple d'un tableau avec 3 lignes et 3 colonnes
tableau2 = np.array([[1,2,3], [4,5,6]])
tableau2

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
# Exemple d'un tableau avec 3 lignes et 3 colonnes
tableau3 = np.array([[1,2,3], [4,5,6], [7,8,9]])
tableau3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

- Utilisation de la fonction <b>range()</b> pour créer un tableau Numpy:

In [5]:
tableau4 = np.array(range(10)) # tableau avec des chiffres de 0 à 9
tableau4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- Utilisation de la fonction <b>zeros()</b> pour créer un tableau Numpy avec des zéros:

In [6]:
tableau5 = np.zeros((4,3)) # tableau contenant 4 lignes et 3 colonnes de 0
tableau5

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

- Utilisation de la fonction <b>ones()</b> pour créer un tableau Numpy avec des 1:

In [7]:
tableau6 = np.ones((4,3)) # tableau contenant 2 lignes 2 colonnes de 1
tableau6

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

- Utilisation de la fonction <b>identity()</b> pour créer une matrice Numpy identité:

In [8]:
tableau7 = np.identity(4) # Matrice Identité de dimension 4
tableau7

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

- Conversion d'une liste en tableau numpy avec la fonction <b>array()</b>

In [9]:
ma_liste = [0,1,2,3,4,5,6]
ma_liste

[0, 1, 2, 3, 4, 5, 6]

In [10]:
tableau8 = np.array(ma_liste)
tableau8

array([0, 1, 2, 3, 4, 5, 6])

- Utilisation de la fonction <b>random()</b> pour créer un tableau Numpy  avec des valeurs aléatoires:

In [11]:
tableau9 = np.random.randint(100,size=(4,3))  # Exemple création d'un tableau 4*3 random avec valeurs comprises entre 0 et 100 
tableau9

array([[79,  6, 97],
       [ 0,  4, 25],
       [97, 63, 38],
       [13, 59, 14]])

## 2- Accéder aux données d'un tableau Numpy ou ndarray

Nous pouvons accéder à un élément individuel ou à une tranche de valeurs (slicing). Semblable aux listes, le premier élément est indexé à 0. Par exemple, array1[0,0] indique que nous accédons à la première ligne et à la première colonne. Le premier nombre du tuple [0,0] indique l’index de la ligne et le deuxième nombre indique l’index de la colonne:


In [12]:
mon_tableau = np.array([[1,2,3], [4,5,6], [7,8,9]])
mon_tableau

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

- Exemples pour accéder à des éléments individuels d'un tableau Numpy:

In [13]:
mon_tableau[1,2]     # On veut accéder à l'élément situé à la ligne d'index 1 et la colonne d'index 2 
                     #  ndarray(row,column) 

6

In [14]:
mon_tableau[1,-1]    # On veut accéder à l'élément situé à la ligne d'index 1 et à la colonne ayant le dernier index

6

In [15]:
mon_tableau[0,1]     # On veut accéder à l'élément situé à la ligne d'index 0 et la colonne d'index 1

2

In [16]:
mon_tableau[1,0]     # On veut accéder à l'élément situé à la ligne d'index 1 et la colonne d'index 0                     

4

- Exemples pour accéder à des tranches d'un tableau Numpy: <b>Slicing</b>

In [17]:
mon_tableau[:,0]    # On veut toutes les lignes de la colonne d'index 0 (slicing)

array([1, 4, 7])

In [18]:
mon_tableau[0,:]    # On veut toutes les colonnes de la ligne d'index 0 (slicing)

array([1, 2, 3])

In [19]:
mon_tableau[:,0:3:2] # On veut toutes les lignes et les colonnes d'index de 0 à 3 avec pas de 2.
                     # Donc toutes les lignes et les colonnes 1 et 2 .

array([[1, 3],
       [4, 6],
       [7, 9]])

In [20]:
mon_tableau[:,-1]  # On veut toutes les lignes de la dernière colonne

array([3, 6, 9])

In [21]:
mon_tableau[:,1:-1] # On veut toutes les lignes entre la colonne d'index 1 et la dernière colonne

array([[2],
       [5],
       [8]])

In [22]:
mon_tableau[2,1:-1] # On veut les valeurs de la ligne d'index 2 entre la colonne d'index 1 et la dernière colonne

array([8])

## 3- Calculs mathématiques et matriciels sur un tableau Numpy: 

Les tableaux Numpy sont très faciles à manipuler: concaténer, ajouter, multiplier, transposer avec une seule ligne de code.
Vous trouverez ci-dessous quelques exemples d’opérations arithmétiques et multiplicatives variées avec les tableaux Numpy. 

In [23]:
array1 = np.arange(9).reshape(3,3)
array1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
array2 = np.random.randint(50, size=(3,3))
array2

array([[41, 19, 44],
       [24, 40, 37],
       [19, 30, 24]])

- Opérations arithmétiques de base: addition, soustraction, multiplication, division

In [25]:
array1 + 10 # ajouter une valeur à tous les éléments

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [26]:
array1 - 10 # soustraire une valeur à tous les éléments

array([[-10,  -9,  -8],
       [ -7,  -6,  -5],
       [ -4,  -3,  -2]])

In [27]:
array1 * 100 # multiplier une valeur à tous les éléments

array([[  0, 100, 200],
       [300, 400, 500],
       [600, 700, 800]])

In [28]:
array1[:,0] * 10 # on multiplie par 10 toutes les lignes de la colonne d'index 0.

array([ 0, 30, 60])

In [29]:
array1 / 2 # diviser une valeur à tous les éléments

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

- quelques fonctions et méthodes Numpy applicables sur les tableaux Numpy:

<a class="reference internal" href="https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.all.html#numpy.all" title="numpy.all"><code class="xref py py-obj docutils literal"><span class="pre">all</span></code></a>,
<a class="reference internal" href="https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.any.html#numpy.any" title="numpy.any"><code class="xref py py-obj docutils literal"><span class="pre">any</span></code></a>,
<a class="reference internal" href="https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.apply_along_axis.html#numpy.apply_along_axis" title="numpy.apply_along_axis"><code class="xref py py-obj docutils literal"><span class="pre">apply_along_axis</span></code></a>,
<a class="reference internal" href="https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.argmax.html#numpy.argmax" title="numpy.argmax"><code class="xref py py-obj docutils literal"><span class="pre">argmax</span></code></a>,
<a class="reference internal" href="https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.argmin.html#numpy.argmin" title="numpy.argmin"><code class="xref py py-obj docutils literal"><span class="pre">argmin</span></code></a>,
<a class="reference internal" href="https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.argsort.html#numpy.argsort" title="numpy.argsort"><code class="xref py py-obj docutils literal"><span class="pre">argsort</span></code></a>,
<a class="reference internal" href="https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.average.html#numpy.average" title="numpy.average"><code class="xref py py-obj docutils literal"><span class="pre">average</span></code></a>,
<a class="reference internal" href="https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.bincount.html#numpy.bincount" title="numpy.bincount"><code class="xref py py-obj docutils literal"><span class="pre">bincount</span></code></a>,
<a class="reference internal" href="https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.ceil.html#numpy.ceil" title="numpy.ceil"><code class="xref py py-obj docutils literal"><span class="pre">ceil</span></code></a>,
<a class="reference internal" href="https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.clip.html#numpy.clip" title="numpy.clip"><code class="xref py py-obj docutils literal"><span class="pre">clip</span></code></a>,
<a class="reference internal" href="https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.conj.html#numpy.conj" title="numpy.conj"><code class="xref py py-obj docutils literal"><span class="pre">conj</span></code></a>,
<a class="reference internal" href="https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.corrcoef.html#numpy.corrcoef" title="numpy.corrcoef"><code class="xref py py-obj docutils literal"><span class="pre">corrcoef</span></code></a>,
<a class="reference internal" href="https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.cov.html#numpy.cov" title="numpy.cov"><code class="xref py py-obj docutils literal"><span class="pre">cov</span></code></a>,
<a class="reference internal" href="https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.cross.html#numpy.cross" title="numpy.cross"><code class="xref py py-obj docutils literal"><span class="pre">cross</span></code></a>,
<a class="reference internal" href="https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.cumprod.html#numpy.cumprod" title="numpy.cumprod"><code class="xref py py-obj docutils literal"><span class="pre">cumprod</span></code></a>,
<a class="reference internal" href="https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.cumsum.html#numpy.cumsum" title="numpy.cumsum"><code class="xref py py-obj docutils literal"><span class="pre">cumsum</span></code></a>,
<a class="reference internal" href="https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.diff.html#numpy.diff" title="numpy.diff"><code class="xref py py-obj docutils literal"><span class="pre">diff</span></code></a>,
<a class="reference internal" href="https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.dot.html#numpy.dot" title="numpy.dot"><code class="xref py py-obj docutils literal"><span class="pre">dot</span></code></a>,
<a class="reference internal" href="https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.floor.html#numpy.floor" title="numpy.floor"><code class="xref py py-obj docutils literal"><span class="pre">floor</span></code></a>,
<a class="reference internal" href="https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.inner.html#numpy.inner" title="numpy.inner"><code class="xref py py-obj docutils literal"><span class="pre">inner</span></code></a>,
<a class="reference internal" href="https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.lexsort.html#numpy.lexsort" title="numpy.lexsort"><code class="xref py py-obj docutils literal"><span class="pre">lexsort</span></code></a>,
<a class="reference external" href="https://docs.python.org/dev/library/functions.html#max" title="(in Python v3.7)"><code class="xref py py-obj docutils literal"><span class="pre">max</span></code></a>,
<a class="reference internal" href="https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.maximum.html#numpy.maximum" title="numpy.maximum"><code class="xref py py-obj docutils literal"><span class="pre">maximum</span></code></a>,
<a class="reference internal" href="https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.mean.html#numpy.mean" title="numpy.mean"><code class="xref py py-obj docutils literal"><span class="pre">mean</span></code></a>,
<a class="reference internal" href="https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.median.html#numpy.median" title="numpy.median"><code class="xref py py-obj docutils literal"><span class="pre">median</span></code></a>,
<a class="reference external" href="https://docs.python.org/dev/library/functions.html#min" title="(in Python v3.7)"><code class="xref py py-obj docutils literal"><span class="pre">min</span></code></a>,
<a class="reference internal" href="https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.minimum.html#numpy.minimum" title="numpy.minimum"><code class="xref py py-obj docutils literal"><span class="pre">minimum</span></code></a>,
<a class="reference internal" href="https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.nonzero.html#numpy.nonzero" title="numpy.nonzero"><code class="xref py py-obj docutils literal"><span class="pre">nonzero</span></code></a>,
<a class="reference internal" href="https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.outer.html#numpy.outer" title="numpy.outer"><code class="xref py py-obj docutils literal"><span class="pre">outer</span></code></a>,
<a class="reference external" href="https://docs.python.org/dev/library/re.html#module-re" title="(in Python v3.7)"><code class="xref py py-obj docutils literal"><span class="pre">re</span></code></a>,
<a class="reference external" href="https://docs.python.org/dev/library/functions.html#round" title="(in Python v3.7)"><code class="xref py py-obj docutils literal"><span class="pre">round</span></code></a>,
<a class="reference internal" href="https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.sort.html#numpy.sort" title="numpy.sort"><code class="xref py py-obj docutils literal"><span class="pre">sort</span></code></a>,
<a class="reference internal" href="https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.std.html#numpy.std" title="numpy.std"><code class="xref py py-obj docutils literal"><span class="pre">std</span></code></a>,
<a class="reference internal" href="https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.sum.html#numpy.sum" title="numpy.sum"><code class="xref py py-obj docutils literal"><span class="pre">sum</span></code></a>,
<a class="reference internal" href="https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.trace.html#numpy.trace" title="numpy.trace"><code class="xref py py-obj docutils literal"><span class="pre">trace</span></code></a>,
<a class="reference internal" href="https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.transpose.html#numpy.transpose" title="numpy.transpose"><code class="xref py py-obj docutils literal"><span class="pre">transpose</span></code></a>,
<a class="reference internal" href="https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.var.html#numpy.var" title="numpy.var"><code class="xref py py-obj docutils literal"><span class="pre">var</span></code></a>,
<a class="reference internal" href="https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.vdot.html#numpy.vdot" title="numpy.vdot"><code class="xref py py-obj docutils literal"><span class="pre">vdot</span></code></a>,
<a class="reference internal" href="https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.vectorize.html#numpy.vectorize" title="numpy.vectorize"><code class="xref py py-obj docutils literal"><span class="pre">vectorize</span></code></a>,
<a class="reference internal" href="https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.where.html#numpy.where" title="numpy.where"><code class="xref py py-obj docutils literal"><span class="pre">where</span></code></a>


In [30]:
np.add(array1,10) # ajouter une valeur à tous les éléments

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [31]:
np.subtract(array1,10) # soustraire une valeur à tous les éléments

array([[-10,  -9,  -8],
       [ -7,  -6,  -5],
       [ -4,  -3,  -2]])

In [32]:
np.multiply(array1,100) # multiplier une valeur à tous les éléments

array([[  0, 100, 200],
       [300, 400, 500],
       [600, 700, 800]])

In [33]:
np.divide(array1, 2) # diviser une valeur à tous les éléments

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [34]:
np.mean(array1) # calcul de la moyenne du tableau Numpy à partir de la fonction mean()

4.0

In [35]:
array1.mean()  # calcul de la moyenne du tableau Numpy à partir de la méthode mean()

4.0

In [36]:
array1.min()  # calcul de la valeur minimale du tableau Numpy à partir de la méthode min()

0

In [37]:
array1.max()  # calcul de la valeur maximale du tableau Numpy à partir de la méthode max()

8

In [38]:
np.mean(array1, axis=0)  # si on veut appliquer une fonction uniquement sur les colonnes 

array([3., 4., 5.])

In [39]:
np.mean(array1, axis=1) # si on veut appliquer une fonction uniquement sur les lignes 

array([1., 4., 7.])

- Opérations entre plusieurs tableaux

In [40]:
(array1 +1) * array2 # multiplication de 2 tableaux

array([[ 41,  38, 132],
       [ 96, 200, 222],
       [133, 240, 216]])

In [41]:
array1 + array2 # somme de 2 tableaux

array([[41, 20, 46],
       [27, 44, 42],
       [25, 37, 32]])

In [42]:
np.dot(array1, array2) # produit scalaire de 2 tableaux

array([[ 62, 100,  85],
       [314, 367, 400],
       [566, 634, 715]])

## 4- Modifier des tableaux Numpy: 

Parmi les autres fonctionnalités intéressantes figurent la concaténation, le fractionnement, la transposition (changement d’éléments d’une rangée à l’autre et vice versa) et l’obtention des éléments en diagonale.

a)- Pour manipuler/modifier les dimensions d'un tableau Numpy: 

La dimension d'un tableau est donnée par le nombres d'élélements suivant chaque axe. 
On a des méthodes spécifiques et des attributs spécifiques aux ndarray():

<table border="1" class="docutils">
<colgroup>
<col width="27%">
<col width="57%">
</colgroup>
<tbody valign="top">

<tr><td><tt class="docutils literal"><span class="pre">ndim</span></tt></td>
<td>Attribut pour connaitre la dimension d'un tableau Numpy</td>
</tr>
<tr><td><tt class="docutils literal"><span class="pre">shape</span></tt></td>
<td>Attribut pour connaitre les dimension d'un tableau Numpy </td>
</tr>
<tr><td><tt class="docutils literal"><span class="pre">dtype</span></tt></td>
<td>Attribut pour connaitre le type de notre array</td>
</tr>
<tr><td><tt class="docutils literal"><span class="pre">size</span></tt></td>
<td>Attibut pour connaitre la taille de notre array</td>
</tr>

</tbody>
</table>




In [43]:
a = np.floor(10*np.random.random((3,4)))
print(a, a.shape, a.ndim)

[[7. 4. 5. 7.]
 [4. 8. 9. 7.]
 [8. 2. 2. 0.]] (3, 4) 2


Selon nos besoins en programmation, on peut modifier la dimension d'un tableau.

In [44]:
a.ravel()  # écrit notre tableau sur 1 dimension (flattened) 

array([7., 4., 5., 7., 4., 8., 9., 7., 8., 2., 2., 0.])

In [45]:
a.reshape(6,2)  # fonction reshape() pour modifier la dimension de notre tableau

array([[7., 4.],
       [5., 7.],
       [4., 8.],
       [9., 7.],
       [8., 2.],
       [2., 0.]])

In [46]:
a.T  # méthode .T pour calculer la transposée de notre tableau. 

array([[7., 4., 8.],
       [4., 8., 2.],
       [5., 9., 2.],
       [7., 7., 0.]])

In [47]:
print(a.T.shape, a.shape)

(4, 3) (3, 4)


La fonction reshape renvoie son argument avec une forme modifiée, alors que la méthode ndarray.resize modifie le tableau lui-même:

In [48]:
a.resize((2,6))
a

array([[7., 4., 5., 7., 4., 8.],
       [9., 7., 8., 2., 2., 0.]])

Si une dimension est définie à -1 dans une opération de reformage, les autres dimensions sont automatiquement calculées:

In [49]:
a.reshape(4,-1)

array([[7., 4., 5.],
       [7., 4., 8.],
       [9., 7., 8.],
       [2., 2., 0.]])

b)- Travailler et modifier un sous-ensemble d'un tableau Numpy:

In [50]:
notre_tableau = np.array([[1,2,3], [4,5,6], [7,8,9]])
notre_tableau

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

On va sélectionner un sous-ensemble de notre tableau en prenant la ligne d'index 0 .

In [51]:
sous_tableau = notre_tableau[0]
sous_tableau

array([1, 2, 3])

On va modifier la première valeur de notre tableau. 

In [52]:
sous_tableau[0] = 100
sous_tableau

array([100,   2,   3])

Mais en modifiant notre sous tableau, on se rend compte que nous avons modifié notre_tableau.

In [53]:
notre_tableau

array([[100,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9]])

Une modification du sous-ensemble entraîne une modification du tableau initial .
On dit que sous_tableau est une vue de notre tableau. Raison: travailler avec des gros volumes de données.

Si on veut vraiment travailler avec un sous ensemble sans modifier notre tableau d'origine, il faut faire une copie avec la fonction <b>copy()</b>.


In [54]:
notre_tableau = np.array([[1,2,3], [4,5,6], [7,8,9]])
sous_tableau=notre_tableau[0].copy()
sous_tableau[0]=101

In [55]:
sous_tableau

array([101,   2,   3])

In [56]:
notre_tableau

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])


   c)- Pour concatener des tableaux Numpy:
    
<a class="reference internal" href="https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.vstack.html#numpy.vstack" title="numpy.vstack"><code class="xref py py-obj docutils literal"><span class="pre">vstack</span></code></a>, 
<a class="reference internal" href="https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.column_stack.html#numpy.column_stack" title="numpy.column_stack"><code class="xref py py-obj docutils literal"><span class="pre">column_stack</span></code></a>, 
<a class="reference internal" href="https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.concatenate.html#numpy.concatenate" title="numpy.concatenate"><code class="xref py py-obj docutils literal"><span class="pre">concatenate</span></code></a>

- Pour concatener des tableaux Numpy: fonction <b>concatenate()</b>

In [57]:
array1=np.array([[1,2,3],[4,5,6],[7,8,9]])
array1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
array2=np.array([[2,5,6],[9,10,11],[5,6,9]])
array2

array([[ 2,  5,  6],
       [ 9, 10, 11],
       [ 5,  6,  9]])

In [59]:
np.concatenate([array1,array2], axis=0)   # concaténer par lignes  (axis = 0) 

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [ 2,  5,  6],
       [ 9, 10, 11],
       [ 5,  6,  9]])

In [60]:
np.concatenate([array1,array2], axis=1)   # concaténer par colonnes  (axis = 1) 

array([[ 1,  2,  3,  2,  5,  6],
       [ 4,  5,  6,  9, 10, 11],
       [ 7,  8,  9,  5,  6,  9]])

Si on souhaite concatener des tableaux n'ayant pas les mêmes dimensions, on ne va pas utiliser 
la fonction concatenate(), mais: 
- la fonction <b>vstack()</b> pour empiler à la verticale
- la fonction <b>hstack()</b> pour empliler à l'horizontale

In [61]:
array3=np.array([10,20,30]) # Création d'un array() de 1D.

In [62]:
array3

array([10, 20, 30])

In [63]:
array4=np.array([[1,2,3],[4,5,6],[7,8,9]]) # Création d'un array() bi-dimentionnel

In [64]:
array4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
#np.concatenate([array3,array4])
np.vstack([array4,array3])   #  On va concatener à la verticale les deux tableaux 

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 20, 30]])

In [66]:
array5=np.array([[10],[20],[30]]) # Tableau à 2 dimensions à 2 colonnes
array5

array([[10],
       [20],
       [30]])

In [67]:
np.hstack([array4,array5]) #  On va empiler à l'horizontale les deux tableaux 

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 20],
       [ 7,  8,  9, 30]])

Une autre fonction intéressante à connaitre est la fonction <b>column_stack()</b>.

Cette fonction empile des tableaux 1D sous forme de colonnes dans un tableau 2D. Cela équivaut à hstack uniquement pour les tableaux 2D.

In [68]:
a = np.array([4.,2.,1.]) # on utilise un tableau 1 D, que nous souhaitons concaténer avec le tableau 2D array4
print(a.shape, array4.shape)
print(a.ndim, array4.ndim)

(3,) (3, 3)
1 2


In [69]:
# np.hstack([array4,a]) # problème de dimension
np.column_stack([array4,a])

array([[1., 2., 3., 4.],
       [4., 5., 6., 2.],
       [7., 8., 9., 1.]])

 d)- Pour découper des tableaux Numpy:

C'est le contraire de la concatenation. 
Nous avons les fonctions split(), hsplit() et vsplit() . 

In [70]:
array=np.array([15,16,17,12,49,52,12,14,36]) # on crée un array à 1 D. 

In [71]:
len(array) # taille de notre array 

9

In [72]:
np.split(array,3) # séparer le tableau array en 3 tableaux

[array([15, 16, 17]), array([12, 49, 52]), array([12, 14, 36])]

On peut découper notre tableau avec des points de cassure délimités par les index. 

In [73]:
np.split(array,[2,6]) # on veut couper notre tableau en 3 tableaux , les chiffres entre [] sont les points de cassures. 
                      # correspond aux index où on coupe. 

[array([15, 16]), array([17, 12, 49, 52]), array([12, 14, 36])]

In [74]:
array1,array2,array3=np.split(array,[2,6]) # on peut multi-assigner notre cassure

In [75]:
print(array1,array2,array3)

[15 16] [17 12 49 52] [12 14 36]


In [76]:
array1,array2,array3,array4=np.split(array,[2,4,6]) # selon le nombre de points de cassure, on a le nombre de tableaux. 

In [77]:
print(array1,array2,array3,array4)

[15 16] [17 12] [49 52] [12 14 36]


Pour casser des tableaux à 2 dimensions. on utilise hsplit ou vsplit. 

In [78]:
array2=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [79]:
array1,array1bis=np.vsplit(array2, [2]) # on coupe à la verticale au point de cassure de niveau 2 
print(array1,array1bis)

[[1 2 3]
 [4 5 6]] [[7 8 9]]


In [80]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
array1,array1bis=np.hsplit(array2,[2]) # on coupe à l'horizontal au point de cassure de niveau 2 
print(array1,array1bis)

[[1 2]
 [4 5]
 [7 8]] [[3]
 [6]
 [9]]


 e)- Pour supprimer des rangées et colonnes des tableaux Numpy: <b>delete()</b> 

In [82]:
array=np.array([[1,2,3],[4,5,6],[7,8,9]])
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
np.delete(array,2,axis=0) # supprime la ligne d'index 2

array([[1, 2, 3],
       [4, 5, 6]])

In [85]:
np.delete(array2,2,axis=1) # supprime la colonne d'index 2

array([[1, 2],
       [4, 5],
       [7, 8]])

f)- Pour calculer la transposer d'un tableau Numpy: <b>transpose()</b> 

In [86]:
np.transpose(array)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

g)- Pour obtenir les valeurs de la diagonale d'un tableau Numpy: <b>diagonal()</b> 

In [87]:
array.diagonal() # obtenir les éléments de la diagonale de array

array([1, 5, 9])

## 5- Comparaisons et masques sur un tableau Numpy: 

Avec les tableaux Numpy, il est possible d'utiliser une matrice booléenne pour filtrer et comparer des tableaux Numpy.

In [88]:
tableau = np.random.randint(100,size=(6,6))  # création d'un tableau 4*3 random avec valeurs comprises entre 0 et 100 
tableau

array([[86, 19, 15, 79, 25, 89],
       [80, 24, 84, 71, 64,  8],
       [67, 58, 32, 20, 48, 19],
       [79, 15, 13,  3, 66, 11],
       [35, 80, 92, 73,  0, 61],
       [22, 63, 54, 78, 72, 56]])

In [89]:
masque = tableau>50# on génère ici un tableau de la même dimension que notre tableau d'origine mais avec des booléens, comme un masque
masque

array([[ True, False, False,  True, False,  True],
       [ True, False,  True,  True,  True, False],
       [ True,  True, False, False, False, False],
       [ True, False, False, False,  True, False],
       [False,  True,  True,  True, False,  True],
       [False,  True,  True,  True,  True,  True]])

Étant tout deux de même dimension, nous pouvons utiliser cette matrice booléenne à notre avantage. Autrement dit, nous pouvons faire du masquage booléen. Avec cette matrice booléenne comme masque, nous pouvons l’utiliser pour sélectionner le sous-ensemble particulier de données qui nous intéresse.

In [90]:
tableau[masque] 
#tableau[tableau>50]  # synthaxe équivalente

array([86, 79, 89, 80, 84, 71, 64, 67, 58, 79, 66, 80, 92, 73, 61, 63, 54,
       78, 72, 56])

 Nous disposons de nombreux autres opérateurs de comparaison pour comparer deux tableaux tels que == (égalité), != (Non-égalité), <= (inférieur ou égal à). Nous pouvons même combiner deux déclarations booléennes & (pour les conditions “ET”) ou | (pour les conditions “OU”).

In [91]:
#tableau[tableau>=50]                 # on souhaite garder uniquement les valeurs supérieures ou égales à  50.
#tableau[tableau<50]                      # on souhaite garder uniquement les valeurs strictement inférieures à 50.
#tableau[tableau!=50]                     # on souhaite garder uniquement les valeurs différentes de 50.
#tableau[tableau==50]                     # on souhaite garder uniquement les valeurs égales 50. 
#tableau[(tableau >=50) & (tableau <=70)]   # on souhaite garder uniquement les valeurs comprises entre 50 et 70 inclusivement.
tableau[(tableau>=50) | (tableau<=40)]     # on souhaite garder uniquement les valeurs non comprises entre 40 et 50. 

array([86, 19, 15, 79, 25, 89, 80, 24, 84, 71, 64,  8, 67, 58, 32, 20, 19,
       79, 15, 13,  3, 66, 11, 35, 80, 92, 73,  0, 61, 22, 63, 54, 78, 72,
       56])

## Exercice sur la librairie de Numpy de Python:
### Objectifs, manipuler des données ascii de stations uniquement avec la librairie Numpy.

Ensemble : lecture du fichier contenant les données journalières de précipitation et de température pour la station d'Ottawa pour l'année 2017 

1- Créer un tableau Numpy ayant une colonne pour la température et une colonne pour la précipitation. (avec deux tableaux Numpy 1D, créer un tableau 2D (365 lignes et 2 colonnes).

2- Convertir les données de températures en Celcius (T[Celcius] = T[Kelvin] - 273.15).

3- Combien de journées ont une accumulation supérieure à 25mm ?

4- Quelle température a été enregistrée pour la journée présentant la plus grande accumulation.

5- Calculer le nombre de degrés jours (>0degC) pour l'année 2017.

6- Calculer le cumul journalier de précipitation pour l'année 2017 et assigner cette variable au tableau cumul_precipitation. Ajouter le tableau cumul_precipitation au tableau.  

7- Juste pour l’exercice, splitter (casser) l’array en 2 tableaux, puis les concaténer à nouveau pour obtenir le tableau initial.


In [92]:
import numpy as np
# pour lire un fichier csv avec numpy: appel de la fonction genfromtxt()
temperature = np.genfromtxt("./DATA/OTTAWA_tasmoy_2017.csv", dtype=float)
precipitation = np.genfromtxt("./DATA/OTTAWA_PrecTOT_2017.csv", dtype=float)

In [93]:
print(temperature.shape, precipitation.shape)

(365,) (365,)


### Corrigé de l'exercice 4:

In [94]:
#1- Créer un tableau Numpy ayant une colonne pour la température et une colonne pour la précipitation. 
#   (avec deux tableaux Numpy 1D, créer un tableau 2D (365 lignes et 2 colonnes).

tableau = np.column_stack([temperature,precipitation])
tableau

array([[2.6665e+02, 1.1000e-01],
       [2.6635e+02, 3.0300e+00],
       [2.7135e+02, 2.6570e+01],
       [2.7395e+02, 4.2100e+00],
       [2.6335e+02, 0.0000e+00],
       [2.6015e+02, 0.0000e+00],
       [2.5615e+02, 1.1000e-01],
       [2.5665e+02, 0.0000e+00],
       [2.5785e+02, 0.0000e+00],
       [2.6865e+02, 1.4370e+01],
       [2.7315e+02, 3.4000e+00],
       [2.7595e+02, 5.9000e-01],
       [2.6535e+02, 0.0000e+00],
       [2.5815e+02, 1.1000e-01],
       [2.6415e+02, 0.0000e+00],
       [2.6785e+02, 0.0000e+00],
       [2.6765e+02, 8.5200e+00],
       [2.7115e+02, 3.4000e-01],
       [2.7315e+02, 0.0000e+00],
       [2.7445e+02, 5.5000e-01],
       [2.7465e+02, 5.4000e-01],
       [2.7465e+02, 0.0000e+00],
       [2.7135e+02, 2.6000e-01],
       [2.7115e+02, 7.3000e+00],
       [2.7185e+02, 2.0300e+00],
       [2.7365e+02, 5.4000e-01],
       [2.7265e+02, 5.1000e-01],
       [2.7115e+02, 2.7900e+00],
       [2.6915e+02, 5.1000e-01],
       [2.5965e+02, 0.0000e+00],
       [2.

In [95]:
#tableau = np.hstack([temperature,precipitation])
tableau = np.hstack([temperature.reshape(len(temperature),-1),precipitation.reshape(len(precipitation),-1)])

In [96]:
tableau

array([[2.6665e+02, 1.1000e-01],
       [2.6635e+02, 3.0300e+00],
       [2.7135e+02, 2.6570e+01],
       [2.7395e+02, 4.2100e+00],
       [2.6335e+02, 0.0000e+00],
       [2.6015e+02, 0.0000e+00],
       [2.5615e+02, 1.1000e-01],
       [2.5665e+02, 0.0000e+00],
       [2.5785e+02, 0.0000e+00],
       [2.6865e+02, 1.4370e+01],
       [2.7315e+02, 3.4000e+00],
       [2.7595e+02, 5.9000e-01],
       [2.6535e+02, 0.0000e+00],
       [2.5815e+02, 1.1000e-01],
       [2.6415e+02, 0.0000e+00],
       [2.6785e+02, 0.0000e+00],
       [2.6765e+02, 8.5200e+00],
       [2.7115e+02, 3.4000e-01],
       [2.7315e+02, 0.0000e+00],
       [2.7445e+02, 5.5000e-01],
       [2.7465e+02, 5.4000e-01],
       [2.7465e+02, 0.0000e+00],
       [2.7135e+02, 2.6000e-01],
       [2.7115e+02, 7.3000e+00],
       [2.7185e+02, 2.0300e+00],
       [2.7365e+02, 5.4000e-01],
       [2.7265e+02, 5.1000e-01],
       [2.7115e+02, 2.7900e+00],
       [2.6915e+02, 5.1000e-01],
       [2.5965e+02, 0.0000e+00],
       [2.

In [97]:
print(tableau.shape)

(365, 2)


In [98]:
#2- Convertir les données de températures en Celcius (T[Celcius] = T[Kelvin] - 273.15).
tableau[:,0]=tableau[:,0]-273.15  # on prend toutes les lignes de la première colonne 

In [99]:
print(tableau)

[[ -6.5    0.11]
 [ -6.8    3.03]
 [ -1.8   26.57]
 [  0.8    4.21]
 [ -9.8    0.  ]
 [-13.     0.  ]
 [-17.     0.11]
 [-16.5    0.  ]
 [-15.3    0.  ]
 [ -4.5   14.37]
 [  0.     3.4 ]
 [  2.8    0.59]
 [ -7.8    0.  ]
 [-15.     0.11]
 [ -9.     0.  ]
 [ -5.3    0.  ]
 [ -5.5    8.52]
 [ -2.     0.34]
 [  0.     0.  ]
 [  1.3    0.55]
 [  1.5    0.54]
 [  1.5    0.  ]
 [ -1.8    0.26]
 [ -2.     7.3 ]
 [ -1.3    2.03]
 [  0.5    0.54]
 [ -0.5    0.51]
 [ -2.     2.79]
 [ -4.     0.51]
 [-13.5    0.  ]
 [-15.     2.03]
 [ -8.5    0.  ]
 [-10.5    0.76]
 [ -7.3    0.  ]
 [ -8.8    2.54]
 [ -3.5    1.52]
 [-12.     7.37]
 [ -4.    19.95]
 [ -5.5    0.  ]
 [-13.5    0.  ]
 [-14.8    3.81]
 [-12.     0.11]
 [ -9.    24.13]
 [ -6.8    0.  ]
 [ -8.5   20.32]
 [ -3.3    3.81]
 [ -5.8    0.  ]
 [ -6.8    0.  ]
 [ -0.3    0.  ]
 [  3.5    0.  ]
 [ -1.8    0.  ]
 [ -4.8    1.56]
 [  2.     0.  ]
 [  7.3    0.  ]
 [  1.8    3.19]
 [  2.    12.37]
 [ -2.3    0.  ]
 [  0.8    0.  ]
 [ -1.3   16.0

In [100]:
# 3- Combien de journées ont une accumulation supérieure à 25mm ?
tableau[tableau[:,1]>=25]    # On filtre toutes les lignes de la 2ème colonne 

D:\Utilisateurs\guillaume\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in greater_equal
  


array([[-1.8 , 26.57],
       [ 2.3 , 25.84],
       [ 3.3 , 28.49],
       [ 4.5 , 31.14],
       [ 8.8 , 35.22],
       [ 8.3 , 40.12],
       [16.  , 25.84],
       [17.3 , 37.26],
       [16.  , 26.04],
       [15.8 , 45.01]])

In [101]:
# pour connaitre le nombre de jours, on utilise la fonction len()
len(tableau[tableau[:,1]>=25])   

D:\Utilisateurs\guillaume\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in greater_equal
  


10

In [102]:
# 4- Quelle température a été enregistrée pour la journée présentant la plus grande accumulation.
precipitation_max = np.nanmax(tableau[:,1]) # on cherche le maximum d'accumulation avec la fonction max()
print(precipitation_max)

45.01


In [103]:
tableau[tableau[:,1] == precipitation_max] # on cherche sur toutes les lignes de la deuxième colonne celle qui correspond à notre variable precipitation_max

array([[15.8 , 45.01]])

In [104]:
# 5- Calculer le nombre de degrés jours (>0degC) pour l'année 2017. 

In [105]:
sum(tableau[:,1][tableau[:,1]>0])

D:\Utilisateurs\guillaume\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in greater
  """Entry point for launching an IPython kernel.


1328.5300000000002

In [106]:
# 6- Calculer le cumul journalier de précipitation pour l'année 2017
cumul_precipitation = np.nancumsum(tableau[:,1])

In [107]:
# Ajouter le tableau cumul_precipitation au tableau. 
tableau = np.column_stack([tableau, cumul_precipitation])
tableau

array([[-6.50000e+00,  1.10000e-01,  1.10000e-01],
       [-6.80000e+00,  3.03000e+00,  3.14000e+00],
       [-1.80000e+00,  2.65700e+01,  2.97100e+01],
       ...,
       [         nan,  0.00000e+00,  1.32726e+03],
       [-2.15000e+01,  1.27000e+00,  1.32853e+03],
       [-2.20000e+01,  0.00000e+00,  1.32853e+03]])

In [110]:
# 7. spliter (casser) l’array en 3 tableaux, puis concaténer à nouveau pour obtenir le tableau initial.

# on assigne les trois tableaux et on fait une coupure horizontale avec la fonction hsplit()
temperature2,precipitation2,cumul2 = np.hsplit(tableau, 3)

In [111]:
# Pour revenir à notre tableau original, on utilise la fonction concatenate avec l'option axis = 1 
tableau_original=np.concatenate([temperature2+273.15, precipitation2], axis = 1)

In [112]:
print(tableau_original)

[[2.6665e+02 1.1000e-01]
 [2.6635e+02 3.0300e+00]
 [2.7135e+02 2.6570e+01]
 [2.7395e+02 4.2100e+00]
 [2.6335e+02 0.0000e+00]
 [2.6015e+02 0.0000e+00]
 [2.5615e+02 1.1000e-01]
 [2.5665e+02 0.0000e+00]
 [2.5785e+02 0.0000e+00]
 [2.6865e+02 1.4370e+01]
 [2.7315e+02 3.4000e+00]
 [2.7595e+02 5.9000e-01]
 [2.6535e+02 0.0000e+00]
 [2.5815e+02 1.1000e-01]
 [2.6415e+02 0.0000e+00]
 [2.6785e+02 0.0000e+00]
 [2.6765e+02 8.5200e+00]
 [2.7115e+02 3.4000e-01]
 [2.7315e+02 0.0000e+00]
 [2.7445e+02 5.5000e-01]
 [2.7465e+02 5.4000e-01]
 [2.7465e+02 0.0000e+00]
 [2.7135e+02 2.6000e-01]
 [2.7115e+02 7.3000e+00]
 [2.7185e+02 2.0300e+00]
 [2.7365e+02 5.4000e-01]
 [2.7265e+02 5.1000e-01]
 [2.7115e+02 2.7900e+00]
 [2.6915e+02 5.1000e-01]
 [2.5965e+02 0.0000e+00]
 [2.5815e+02 2.0300e+00]
 [2.6465e+02 0.0000e+00]
 [2.6265e+02 7.6000e-01]
 [2.6585e+02 0.0000e+00]
 [2.6435e+02 2.5400e+00]
 [2.6965e+02 1.5200e+00]
 [2.6115e+02 7.3700e+00]
 [2.6915e+02 1.9950e+01]
 [2.6765e+02 0.0000e+00]
 [2.5965e+02 0.0000e+00]
